// app/layout.tsx
import type { Metadata } from "next";

import HeadComponent from './_component/HeadComponent';
import ReduxProvider from "./_component/ReduxProvider";

import AuthChecker from './_component/AuthChecker';
import KakaoScript from './_component/KakaoScript';
import GlobalStyle from './GlobalStyle';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <HeadComponent /> 
            <body>
                <ReduxProvider>
                    <GlobalStyle />
                    <AuthChecker />
                    {children}
                    <KakaoScript />
                </ReduxProvider>
            </body>
        </html>
    );
}
